controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

home:
  path: /
  controller: App\Controller\HomeController::index

blog_show:
  path:       /blog/{slug}
  controller: App\Controller\LuckyController::show

nico_forest_bundle:
  resource: '@SymfonyForestAdminBundle/config/routes'
  type: directory
